CC=gcc
CFLAGS=-g -Wall -O0

.PHONY: default
default: sum1 sum2 mult-ijk mult-kji mult-ikj

sum1:

sum2:

mult-ijk:

mult-kji:

mult-ikj:

.PHONY: clean
clean:
	rm -f *.o sum1 sum2 mult-ijk mult-kji mult-ikj
	# remove debug symbols directory generated in macOS
	rm -rf *.dSYM

.PHONY: all
all: clean default
